/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Camera: typeof import('./src/components/Camera.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    ElBotton: typeof import('element-plus/es')['ElBotton']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialag: typeof import('element-plus/es')['ElDialag']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDiolag: typeof import('element-plus/es')['ElDiolag']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FileItem: typeof import('./src/components/FileItem.vue')['default']
    Files: typeof import('./src/components/Files.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputCode: typeof import('./src/components/InputCode.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Qrcode: typeof import('./src/components/Qrcode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screen: typeof import('./src/components/Screen.vue')['default']
    TabTransition: typeof import('./src/components/TabTransition.vue')['default']
    Texts: typeof import('./src/components/Texts.vue')['default']
    Video: typeof import('./src/components/Video.vue')['default']
    VideoItem: typeof import('./src/components/VideoItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
